// expense-expert-rn/src/features/expenses/components/ExpenseForm.tsx
import React, { useState } from 'react';
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useExpenses } from '../hooks/useExpenses';
import { AmountInput } from './AmountInput';
import { CategoryCardPicker } from './CategoryCardPicker';
import { DateSelector } from './DateSelector';
import { Expense } from '../types/expense.types';
import { ExpenseCategory, EXPENSE_CATEGORIES } from '../types/category.types';
import { formatCents, fromCents, toCents } from '../utils/currency.util';
import { formatDisplayDate, toDateInputValue } from '../utils/date.util';

export interface ExpenseFormProps {
  initialData?: Partial<Expense>;
  onSuccess?: (expense: Expense) => void;
  onCancel?: () => void;
  testID?: string;
}

const TITLE_SUGGESTIONS = [
  'Grocery',
  'Coffee',
  'Transport',
  'Utilities',
  'Shopping',
  'Dinner',
  'Medicine',
];

/**
 * 3-step transaction entry wizard form matching the Angular application workflow.
 */
export const ExpenseForm: React.FC<ExpenseFormProps> = ({
  initialData,
  onSuccess,
  onCancel,
  testID = 'expense-form',
}) => {
  let router: any;
  try {
    router = useRouter();
  } catch {
    router = null;
  }

  const { addExpense, updateExpense } = useExpenses();

  const isEditMode = Boolean(initialData?.id);
  const [currentStep, setCurrentStep] = useState<1 | 2 | 3>(1);
  const [amount, setAmount] = useState<string>(
    initialData?.amount != null ? String(initialData.amount) : ''
  );
  const [category, setCategory] = useState<string>(
    initialData?.category || ExpenseCategory.Food
  );
  const [title, setTitle] = useState<string>(initialData?.title || '');
  const [date, setDate] = useState<string>(
    initialData?.date
      ? toDateInputValue(initialData.date)
      : toDateInputValue(new Date())
  );
  const [description, setDescription] = useState<string>(
    initialData?.description || ''
  );
  const [isLoan, setIsLoan] = useState<boolean>(initialData?.isLoan || false);
  const [loanPersonId, setLoanPersonId] = useState<string | null>(
    initialData?.loanPersonId || null
  );
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const canProceedStep1 = toCents(amount) > 0 && Boolean(category);
  const canProceedStep2 = title.trim().length > 0 && Boolean(date);
  const canProceed =
    currentStep === 1
      ? canProceedStep1
      : currentStep === 2
      ? canProceedStep2
      : canProceedStep1 && canProceedStep2;

  const handleNext = () => {
    if (currentStep === 1 && canProceedStep1) {
      setCurrentStep(2);
    } else if (currentStep === 2 && canProceedStep2) {
      setCurrentStep(3);
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep((prev) => (prev - 1) as 1 | 2 | 3);
    }
  };

  const handleClose = () => {
    if (onCancel) {
      onCancel();
    } else if (router?.back) {
      router.back();
    }
  };

  const handleSubmit = async () => {
    if (!canProceed || isSubmitting) return;

    setIsSubmitting(true);
    setErrorMessage(null);

    try {
      const dto = {
        title: title.trim(),
        description: description.trim() || undefined,
        amount: fromCents(toCents(amount)),
        category,
        date: new Date(date + 'T00:00:00.000Z').toISOString(),
        isLoan,
        loanPersonId: isLoan ? loanPersonId : null,
      };

      let savedExpense: Expense;

      if (isEditMode && initialData?.id) {
        await updateExpense(initialData.id, dto);
        savedExpense = {
          ...initialData,
          ...dto,
          id: initialData.id,
          amountInCents: toCents(amount),
          month: date.slice(0, 7),
          updatedAt: new Date().toISOString(),
        } as Expense;
      } else {
        savedExpense = await addExpense(dto);
      }

      if (onSuccess) {
        onSuccess(savedExpense);
      } else if (router?.back) {
        router.back();
      }
    } catch (err: any) {
      setErrorMessage(err?.message || 'Failed to save expense');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Find category icon and label for summary card
  const selectedCategoryMeta = EXPENSE_CATEGORIES.find(
    (c) => c.value === category
  ) || { label: category, icon: '📁' };

  return (
    <View testID={testID} className="flex-1 max-w-lg mx-auto w-full pb-8">
      {/* Header Navigation */}
      <View className="flex-row items-center justify-between mb-6 px-1">
        <View className="flex-row items-center gap-3">
          {currentStep > 1 ? (
            <Pressable
              testID="expense-back-btn"
              accessibilityRole="button"
              accessibilityLabel="Go back to previous step"
              onPress={handlePrevious}
              className="p-2 rounded-full bg-slate-100 dark:bg-slate-800 active:bg-slate-200 dark:active:bg-slate-700"
            >
              <Text className="text-base text-slate-700 dark:text-slate-300">←</Text>
            </Pressable>
          ) : null}
          <Text className="text-2xl font-bold text-slate-900 dark:text-slate-100">
            {isEditMode ? 'Edit Expense' : 'Add Expense'}
          </Text>
        </View>

        <Pressable
          testID="expense-cancel-btn"
          accessibilityRole="button"
          accessibilityLabel="Cancel expense entry"
          onPress={handleClose}
          className="p-2 rounded-full active:bg-slate-100 dark:active:bg-slate-800"
        >
          <Text className="text-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
            ✕
          </Text>
        </Pressable>
      </View>

      {/* 3-Step Progress Indicator */}
      <View className="flex-row gap-2 mb-6 px-1">
        {[1, 2, 3].map((step) => (
          <View
            key={step}
            testID={`progress-step-${step}`}
            className={`h-1.5 flex-1 rounded-full ${
              currentStep >= step
                ? 'bg-indigo-600 dark:bg-indigo-500'
                : 'bg-slate-200 dark:bg-slate-700'
            }`}
          />
        ))}
      </View>

      {/* Error Banner */}
      {errorMessage ? (
        <View
          testID="expense-form-error"
          className="bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800/50 rounded-2xl p-4 mb-4"
        >
          <Text className="text-xs font-semibold text-rose-600 dark:text-rose-400 text-center">
            {errorMessage}
          </Text>
        </View>
      ) : null}

      {/* STEP 1: Amount & Category */}
      {currentStep === 1 ? (
        <View testID="expense-step-1" className="space-y-6">
          <View className="items-center mb-2">
            <Text className="text-xl font-bold text-slate-900 dark:text-white">
              How much did you spend?
            </Text>
            <Text className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Enter the amount and pick a category.
            </Text>
          </View>

          <AmountInput
            value={amount}
            onChangeText={setAmount}
            testID="expense-amount-input"
          />

          <View className="space-y-3">
            <Text className="text-sm font-medium text-slate-700 dark:text-slate-300">
              Category
            </Text>
            <CategoryCardPicker
              selectedValue={category}
              onSelect={setCategory}
              testID="expense-category-picker"
            />
          </View>
        </View>
      ) : null}

      {/* STEP 2: Title & Date */}
      {currentStep === 2 ? (
        <View testID="expense-step-2" className="space-y-6">
          <View className="items-center mb-2">
            <Text className="text-xl font-bold text-slate-900 dark:text-white">
              What was it for?
            </Text>
            <Text className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Enter a title and select the date.
            </Text>
          </View>

          <View className="space-y-5 bg-white dark:bg-slate-800 rounded-3xl p-6 shadow-sm border border-slate-100 dark:border-slate-700/50">
            <View>
              <Text className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                Title
              </Text>
              <TextInput
                testID="expense-title-input"
                value={title}
                onChangeText={setTitle}
                placeholder="e.g., Grocery shopping"
                placeholderTextColor="#94a3b8"
                className="w-full rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-900/50 text-slate-900 dark:text-slate-100 px-4 py-3 text-sm outline-none"
              />

              {/* Title Suggestions */}
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                className="mt-3"
                contentContainerStyle={{ gap: 8 }}
              >
                {TITLE_SUGGESTIONS.map((suggestion) => (
                  <Pressable
                    key={suggestion}
                    testID={`suggestion-pill-${suggestion}`}
                    onPress={() => setTitle(suggestion)}
                    className="rounded-full bg-slate-100 dark:bg-slate-700 px-3 py-1.5 active:bg-slate-200 dark:active:bg-slate-600"
                  >
                    <Text className="text-xs font-medium text-slate-600 dark:text-slate-300">
                      {suggestion}
                    </Text>
                  </Pressable>
                ))}
              </ScrollView>
            </View>

            <DateSelector
              value={date}
              onChange={setDate}
              testID="expense-date-selector"
            />
          </View>
        </View>
      ) : null}

      {/* STEP 3: Details & Summary */}
      {currentStep === 3 ? (
        <View testID="expense-step-3" className="space-y-6">
          <View className="items-center mb-2">
            <Text className="text-xl font-bold text-slate-900 dark:text-white">
              Almost done!
            </Text>
            <Text className="text-sm text-slate-500 dark:text-slate-400 mt-1">
              Add any extra details.
            </Text>
          </View>

          <View className="space-y-5 bg-white dark:bg-slate-800 rounded-3xl p-6 shadow-sm border border-slate-100 dark:border-slate-700/50">
            <View>
              <Text className="text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                Note (Optional)
              </Text>
              <TextInput
                testID="expense-description-input"
                value={description}
                onChangeText={setDescription}
                multiline
                numberOfLines={3}
                placeholder="Add more details..."
                placeholderTextColor="#94a3b8"
                textAlignVertical="top"
                className="w-full rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-900/50 text-slate-900 dark:text-slate-100 px-4 py-3 text-sm outline-none min-h-[80px]"
              />
            </View>

            {/* Review Summary Card */}
            <View
              testID="expense-summary-card"
              className="bg-slate-50 dark:bg-slate-900 p-4 rounded-2xl border border-slate-100 dark:border-slate-800"
            >
              <Text className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3">
                Summary
              </Text>
              <View className="flex-row justify-between items-center mb-2">
                <Text
                  testID="expense-summary-title"
                  numberOfLines={1}
                  className="text-sm font-medium text-slate-700 dark:text-slate-300 flex-1 mr-2"
                >
                  {title || 'Untitled'}
                </Text>
                <Text
                  testID="expense-summary-amount"
                  className="text-base font-bold text-slate-900 dark:text-white"
                >
                  {formatCents(toCents(amount))}
                </Text>
              </View>
              <View className="flex-row justify-between items-center text-xs text-slate-500 dark:text-slate-400 pt-1 border-t border-slate-200/50 dark:border-slate-800">
                <Text testID="expense-summary-category" className="text-xs text-slate-500 dark:text-slate-400">
                  {selectedCategoryMeta.icon} {selectedCategoryMeta.label}
                </Text>
                <Text testID="expense-summary-date" className="text-xs text-slate-500 dark:text-slate-400">
                  {formatDisplayDate(date)}
                </Text>
              </View>
            </View>
          </View>
        </View>
      ) : null}

      {/* Sticky / Bottom Action Bar */}
      <View className="mt-8 pt-4">
        {currentStep < 3 ? (
          <Pressable
            testID="expense-continue-btn"
            accessibilityRole="button"
            accessibilityState={{ disabled: !canProceed }}
            disabled={!canProceed}
            onPress={handleNext}
            className={`w-full rounded-2xl py-4 items-center justify-center shadow-lg transition-all active:scale-[0.98] ${
              canProceed
                ? 'bg-indigo-600 dark:bg-indigo-500 shadow-indigo-500/30'
                : 'bg-slate-300 dark:bg-slate-700 opacity-60 shadow-none'
            }`}
          >
            <Text className="text-base font-bold text-white">Continue</Text>
          </Pressable>
        ) : (
          <Pressable
            testID="expense-submit-btn"
            accessibilityRole="button"
            accessibilityState={{ disabled: !canProceed || isSubmitting }}
            disabled={!canProceed || isSubmitting}
            onPress={handleSubmit}
            className={`w-full rounded-2xl py-4 items-center justify-center shadow-lg transition-all active:scale-[0.98] ${
              !canProceed || isSubmitting
                ? 'bg-slate-300 dark:bg-slate-700 opacity-60 shadow-none'
                : 'bg-emerald-600 dark:bg-emerald-500 shadow-emerald-500/30'
            }`}
          >
            {isSubmitting ? (
              <ActivityIndicator color="#ffffff" testID="expense-submit-spinner" />
            ) : (
              <Text className="text-base font-bold text-white">
                {isEditMode ? 'Update Expense' : 'Save Expense'}
              </Text>
            )}
          </Pressable>
        )}
      </View>
    </View>
  );
};

// expense-expert/src/app/features/expenses/expense-form/expense-form.component.ts
import { Component, inject, signal, OnInit, computed } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ExpenseService } from '../../../core/services/expense.service';
import { PersonService } from '../../../core/services/person.service';
import { ToastService } from '../../../core/services/toast.service';
import { ExpenseCategory, Expense } from '../../../core/models/expense.model';
import { Person } from '../../../core/models/person.model';
import { PersonSelectComponent } from '../../../shared/components/person-select/person-select.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { CategoryCardPickerComponent } from '../../../shared/components/category-card-picker/category-card-picker.component';

@Component({
  selector: 'app-expense-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    PersonSelectComponent,
    LoadingSpinnerComponent,
    CategoryCardPickerComponent,
  ],
  template: `
    <div class="max-w-lg mx-auto pb-36">
      <div class="flex items-center justify-between mb-6">
        <div class="flex items-center gap-3">
          @if (currentStep() > 1) {
            <button
              type="button"
              (click)="previousStep()"
              class="p-2 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-500 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
              </svg>
            </button>
          }
          <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">
            {{ isEditMode() ? 'Edit Expense' : 'Add Expense' }}
          </h1>
        </div>
        <button
          type="button"
          (click)="router.navigate(['/expenses'])"
          class="p-2 rounded-full text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Step Indicator -->
      <div class="flex gap-2 mb-8 px-2">
        @for (step of steps; track step) {
          <div
            class="h-1.5 flex-1 rounded-full transition-all duration-300"
            [class.bg-primary-500]="currentStep() >= step"
            [class.bg-gray-200]="currentStep() < step"
            [class.dark:bg-gray-700]="currentStep() < step"
          ></div>
        }
      </div>

      @if (formLoading()) {
        <app-loading-spinner size="lg" [fullPage]="true" />
      } @else {
        <form [formGroup]="form" (ngSubmit)="onSubmit()">

          <!-- STEP 1: Amount & Category -->
          @if (currentStep() === 1) {
            <div class="space-y-6">
              <div class="text-center mb-2">
                <h2 class="text-xl font-bold text-gray-900 dark:text-white">How much did you spend?</h2>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Enter the amount and pick a category.</p>
              </div>

              <div class="bg-white dark:bg-gray-800 rounded-3xl p-6 shadow-sm border border-gray-100 dark:border-gray-700/50">
                <label class="block text-sm font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3 text-center">Amount</label>
                <div class="relative">
                  <span class="absolute left-4 top-1/2 -translate-y-1/2 text-xl text-gray-400">$</span>
                  <input
                    formControlName="amount"
                    type="number"
                    min="0.01"
                    step="0.01"
                    class="w-full rounded-2xl border border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-900/50 text-gray-900 dark:text-gray-100 pl-10 pr-4 py-4 text-3xl font-bold text-center focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 outline-none transition-all"
                    placeholder="0.00"
                  />
                </div>
              </div>

              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">Category</label>
                <app-category-card-picker
                  [selectedValue]="form.get('category')?.value"
                  (selected)="form.patchValue({ category: $event })"
                />
              </div>
            </div>
          }

          <!-- STEP 2: Title & Date -->
          @if (currentStep() === 2) {
            <div class="space-y-6">
              <div class="text-center mb-2">
                <h2 class="text-xl font-bold text-gray-900 dark:text-white">What was it for?</h2>
              </div>

              <div class="space-y-5 bg-white dark:bg-gray-800 rounded-3xl p-6 shadow-sm border border-gray-100 dark:border-gray-700/50">
                <div>
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Title</label>
                  <input
                    formControlName="title"
                    class="w-full rounded-xl border border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-900/50 text-gray-900 dark:text-gray-100 px-4 py-3 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none transition-all"
                    placeholder="e.g., Grocery shopping"
                  />

                  <!-- Smart Suggestions -->
                  <div class="flex gap-2 mt-2 overflow-x-auto pb-1 scrollbar-hide">
                    @for (suggestion of titleSuggestions; track suggestion) {
                      <button
                        type="button"
                        (click)="form.patchValue({ title: suggestion })"
                        class="whitespace-nowrap rounded-full bg-gray-100 dark:bg-gray-700 px-3 py-1 text-xs font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
                      >
                        {{ suggestion }}
                      </button>
                    }
                  </div>
                </div>

                <div>
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Date</label>
                  <input
                    formControlName="date"
                    type="date"
                    class="w-full appearance-none min-w-0 block box-border rounded-xl border border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-900/50 text-gray-900 dark:text-gray-100 px-4 py-3 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none transition-all"
                  />
                </div>
              </div>
            </div>
          }

          <!-- STEP 3: Details & Loan -->
          @if (currentStep() === 3) {
            <div class="space-y-6">
              <div class="text-center mb-2">
                <h2 class="text-xl font-bold text-gray-900 dark:text-white">Almost done!</h2>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Add any extra details.</p>
              </div>

              <div class="space-y-5 bg-white dark:bg-gray-800 rounded-3xl p-6 shadow-sm border border-gray-100 dark:border-gray-700/50">
                <div>
                  <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Note (Optional)</label>
                  <textarea
                    formControlName="description"
                    rows="3"
                    class="w-full rounded-xl border border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-900/50 text-gray-900 dark:text-gray-100 px-4 py-3 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none resize-none transition-all"
                    placeholder="Add more details..."
                  ></textarea>
                </div>



                <!-- Summary Card -->
                <div class="bg-gray-50 dark:bg-gray-900 p-4 rounded-2xl mt-4 border border-gray-100 dark:border-gray-800">
                  <h3 class="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-3">Summary</h3>
                  <div class="flex justify-between mb-2">
                    <span class="text-sm text-gray-600 dark:text-gray-300">{{ form.get('title')?.value || 'Untitled' }}</span>
                    <span class="text-sm font-bold text-gray-900 dark:text-white">{{ form.get('amount')?.value | currency }}</span>
                  </div>
                  <div class="flex justify-between text-xs text-gray-500">
                    <span>{{ form.get('category')?.value }}</span>
                    <span>{{ form.get('date')?.value }}</span>
                  </div>
                </div>
              </div>
            </div>
          }

          <!-- Fixed Bottom Action Bar -->
          <div class="fixed bottom-[72px] left-0 right-0 p-4 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md border-t border-gray-200 dark:border-gray-800 z-10 md:static md:bg-transparent md:p-0 md:border-t-0 md:backdrop-blur-none md:mt-8 md:pt-4">
            <div class="max-w-lg mx-auto flex gap-3">
              @if (currentStep() < totalSteps) {
                <button
                  type="button"
                  (click)="nextStep()"
                  [disabled]="!canProceed()"
                  class="w-full rounded-2xl bg-primary-600 px-4 py-4 text-base font-bold text-white shadow-lg shadow-primary-500/30 hover:bg-primary-700 hover:shadow-primary-500/40 disabled:opacity-50 disabled:shadow-none transition-all active:scale-[0.98]"
                >
                  Continue
                </button>
              } @else {
                <button
                  type="submit"
                  [disabled]="form.invalid || isSaving()"
                  class="w-full rounded-2xl bg-green-600 px-4 py-4 text-base font-bold text-white shadow-lg shadow-green-500/30 hover:bg-green-700 hover:shadow-green-500/40 disabled:opacity-50 disabled:shadow-none transition-all active:scale-[0.98]"
                >
                  {{ isSaving() ? 'Saving...' : (isEditMode() ? 'Update Expense' : 'Save Expense') }}
                </button>
              }
            </div>
          </div>
        </form>
      }
    </div>
  `,
})
export class ExpenseFormComponent implements OnInit {
  private fb = inject(FormBuilder);
  private expenseService = inject(ExpenseService);
  private personService = inject(PersonService);
  private toastService = inject(ToastService);
  private route = inject(ActivatedRoute);
  router = inject(Router);

  persons = signal<Person[]>([]);
  isEditMode = signal(false);
  formLoading = signal(false);
  isSaving = signal(false);

  currentStep = signal(1);
  totalSteps = 3;
  steps = [1, 2, 3];

  titleSuggestions = ['Grocery', 'Coffee', 'Transport', 'Utilities', 'Shopping'];

  private expenseId: string | null = null;

  form: FormGroup = this.fb.group({
    title: ['', Validators.required],
    description: [''],
    amount: [null, [Validators.required, Validators.min(0.01)]],
    category: [ExpenseCategory.Other, Validators.required],
    date: [new Date().toISOString().split('T')[0], Validators.required],
    isLoan: [false],
    loanPersonId: [null],
  });

  ngOnInit(): void {
    this.personService.getPersons().subscribe((persons) => this.persons.set(persons));

    this.expenseId = this.route.snapshot.paramMap.get('id');
    if (this.expenseId) {
      this.isEditMode.set(true);
      this.formLoading.set(true);
      this.expenseService.getExpenseById(this.expenseId).subscribe((expense) => {
        if (expense) {
          this.form.patchValue({
            title: expense.title,
            description: expense.description,
            amount: expense.amount,
            category: expense.category,
            date: this.toDateString(expense.date),
            isLoan: expense.isLoan,
            loanPersonId: expense.loanPersonId,
          });
        }
        this.formLoading.set(false);
      });
    }
  }

  canProceed(): boolean {
    const step = this.currentStep();
    if (step === 1) {
      const amt = this.form.get('amount')?.value;
      return amt != null && amt > 0 && !!this.form.get('category')?.value;
    }
    if (step === 2) {
      return this.form.get('title')?.valid || false;
    }
    return true;
  }

  nextStep() {
    if (this.canProceed() && this.currentStep() < this.totalSteps) {
      this.currentStep.update(v => v + 1);
    }
  }

  previousStep() {
    if (this.currentStep() > 1) {
      this.currentStep.update(v => v - 1);
    }
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) return;

    this.isSaving.set(true);
    const values = this.form.value;

    try {
      const dto = {
        title: values.title,
        description: values.description || '',
        amount: Number(values.amount),
        category: values.category,
        date: new Date(values.date),
        isLoan: values.isLoan || false,
        loanPersonId: values.isLoan ? values.loanPersonId : null,
      };

      if (this.isEditMode() && this.expenseId) {
        await this.expenseService.updateExpense(this.expenseId, dto);
        this.toastService.success('Expense updated');
      } else {
        await this.expenseService.addExpense(dto);
        this.toastService.success('Expense added');
      }
      this.router.navigate(['/expenses']);
    } catch (error: any) {
      this.toastService.error(error.message || 'Failed to save expense');
    } finally {
      this.isSaving.set(false);
    }
  }

  async onAddPerson(name: string): Promise<void> {
    try {
      const id = await this.personService.addPerson(name);
      this.form.patchValue({ loanPersonId: id });
      this.toastService.success('Added "' + name + '"');
    } catch {
      this.toastService.error('Failed to add person');
    }
  }

  private toDateString(date: any): string {
    const d = date instanceof Date ? date : date?.toDate ? date.toDate() : new Date(date);
    return d.toISOString().split('T')[0];
  }
}
