// expense-expert-rn/src/features/auth/components/AuthLayout.tsx
import React from 'react';
import {
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  ScrollView,
  Text,
  View,
} from 'react-native';

export interface AuthLayoutProps {
  title?: string;
  subtitle?: string;
  children: React.ReactNode;
  testID?: string;
}

export const AuthLayout: React.FC<AuthLayoutProps> = ({
  title,
  subtitle,
  children,
  testID = 'auth-layout',
}) => {
  return (
    <SafeAreaView className="flex-1 bg-slate-50 dark:bg-slate-900" testID={testID}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        className="flex-1"
      >
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingVertical: 32,
            paddingHorizontal: 16,
          }}
          keyboardShouldPersistTaps="handled"
        >
          <View className="w-full max-w-md">
            {/* Brand Header */}
            <View className="items-center mb-8">
              <View
                testID="auth-brand-badge"
                className="items-center justify-center h-14 w-14 rounded-2xl bg-primary-600 shadow-md mb-4"
              >
                <Text className="text-white font-bold text-xl">EE</Text>
              </View>
              <Text className="text-2xl font-bold text-slate-900 dark:text-slate-100">
                Expense Expert
              </Text>
              <Text className="text-sm text-slate-500 dark:text-slate-400 mt-1">
                Track your expenses smarter
              </Text>
            </View>

            {/* Auth Card */}
            <View className="w-full bg-white dark:bg-slate-800 rounded-2xl shadow-xl border border-slate-100 dark:border-slate-700 p-6 sm:p-8">
              {title ? (
                <Text className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-1">
                  {title}
                </Text>
              ) : null}
              {subtitle ? (
                <Text className="text-slate-500 dark:text-slate-400 text-sm mb-6">
                  {subtitle}
                </Text>
              ) : null}
              {children}
            </View>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

// expense-expert/src/app/features/auth/auth-layout/auth-layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ToastContainerComponent } from '../../../shared/components/toast-container/toast-container.component';

@Component({
  selector: 'app-auth-layout',
  standalone: true,
  imports: [RouterOutlet, ToastContainerComponent],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-blue-100 dark:from-gray-900 dark:to-gray-800 px-4 transition-colors">
      <div class="w-full max-w-md">
        <!-- Logo -->
        <div class="text-center mb-8">
          <div class="inline-flex items-center justify-center h-14 w-14 rounded-2xl bg-primary-600 text-white font-bold text-xl mb-4">
            EE
          </div>
          <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">Expense Expert</h1>
          <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Track your expenses smarter</p>
        </div>

        <!-- Content card -->
        <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-xl p-5 sm:p-8 transition-colors">
          <router-outlet />
        </div>
      </div>
    </div>

    <app-toast-container />
  `,
})
export class AuthLayoutComponent {}
